<?php

declare(strict_types=1);

namespace Cresset\Wick;

// GENERATED by scripts/publish-composer-branch.sh — the wick binary version
// this Composer package installs. Always matches the package's git tag, so
// `composer require cresset/wick:0.2.1` fetches the wick-v0.2.1 binary.
const WICK_VERSION = '0.2.1';
