#!/usr/bin/env bash
# Regenerate the orphan `composer` branch — the Packagist package for
# cresset-tools/wick — from packaging/composer/, stamp the wick version it
# fetches, commit it as an orphan (no Rust history or source), tag
# v<version>, and push branch + tag to origin.
#
# The branch is force-updated each release (its history is always a single
# commit); the per-version tag is what Packagist serves. Run from a checkout
# of the wick repo with push access to origin.
#
# Usage: scripts/publish-composer-branch.sh <version>   # e.g. 0.2.1
set -euo pipefail

VERSION="${1:?usage: publish-composer-branch.sh <version, e.g. 0.2.1>}"
ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

# Assemble the package tree exactly as it should appear at the repo root on
# the composer branch (no Rust, no packaging/ nesting).
cp -R packaging/composer/. "$STAGE/"
cp LICENSE "$STAGE/LICENSE"

# Stamp the version the launcher fetches (matches the git tag we create).
cat > "$STAGE/src/version.php" <<PHP
<?php

declare(strict_types=1);

namespace CressetTools\\Wick;

// GENERATED by scripts/publish-composer-branch.sh — the wick binary version
// this Composer package installs. Always matches the package's git tag.
const WICK_VERSION = '${VERSION}';
PHP

# Build an orphan commit from \$STAGE via a throwaway index, without touching
# the working tree, HEAD, or the real staged index.
TMP_INDEX="$(mktemp -u)"
GIT_INDEX_FILE="$TMP_INDEX" git --work-tree="$STAGE" add -A
TREE_SHA="$(GIT_INDEX_FILE="$TMP_INDEX" git --work-tree="$STAGE" write-tree)"
rm -f "$TMP_INDEX"

# Fixed identity + date so the orphan commit is fully reproducible: the same
# version always yields the same commit SHA, in CI or locally. Regenerating an
# already-published version is then a no-op (force-push lands the same SHA)
# rather than churning the tag.
export GIT_AUTHOR_NAME="cresset-bot" GIT_AUTHOR_EMAIL="noreply@cresset.tools"
export GIT_COMMITTER_NAME="cresset-bot" GIT_COMMITTER_EMAIL="noreply@cresset.tools"
export GIT_AUTHOR_DATE="2020-01-01T00:00:00 +0000"
export GIT_COMMITTER_DATE="2020-01-01T00:00:00 +0000"

COMMIT_SHA="$(git commit-tree "$TREE_SHA" \
    -m "chore(composer): cresset-tools/wick ${VERSION} (fetches wick-v${VERSION})")"

git branch -f composer "$COMMIT_SHA"
git tag -f "v${VERSION}" "$COMMIT_SHA"

git push -f origin composer
git push -f origin "v${VERSION}"

echo "published composer branch + tag v${VERSION} (launcher fetches wick-v${VERSION})"
