<?php

declare(strict_types=1);

namespace Cresset\Wick;

// GENERATED by scripts/publish-composer-branch.sh — the wick binary version
// this Composer package installs. Always matches the package's git tag.
const WICK_VERSION = '0.3.0';
